title: "My Data World !!"
author: "Harshit Verma"
description: "This blog is going about data, databases and it's flavors. In today's world, as data is everything so let's dive deep into it 
and bring some information to maintain, preserve, optimize and secure and admin same data with the help of available databases flavors." 

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "harshitsaverma@gmail.com"
#twitter_username: "twitteruser"
#github_username: "githubuser"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
